{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-app.serviceAccountName" . }}
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
    environment: {{ .Values.environment }}
{{- end }} 